carts/urls.py
from django.urls import re_path
from django.urls import path

app_name = "carts"


from carts.views import (
    cart_home,
    cart_update,    
    checkout_home,
    checkout_done_view,
)


urlpatterns = [
    
    path('', cart_home, name="home"),
    path('checkout/success/', checkout_done_view, name="success"),
    path('checkout/', checkout_home, name="checkout"),
    path('update/', cart_update, name="update"), 

]

mainapp_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# sarebbe meglio importarle nominativamente
# from . import views
from .views import home_page, about_page, contact_page

# per gli static files
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

from carts.views import cart_home

# from accounts.views import login_page #   this is now substituted by Login View   , register_page  # substituted by RegsigterView

from django.contrib.auth.views import LogoutView

from accounts.views import guest_register_view

from addresses.views  import checkout_address_create_view
from addresses.views  import checkout_address_reuse_view

from carts.views import cart_detail_api_view

from accounts.views import RegisterView
from accounts.views import LoginView

# from products.views import (
#     ProductListView, 
#     product_list_view, 
#     ProductDetailView, 
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
# )


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),
    # path('login/', login_page, name="login"),
    path('login/', LoginView.as_view(), name="login"),
    # path('register/', register_page, name="register"),
    path('register/', RegisterView.as_view(), name="register"),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),

    path('', include("products.urls", namespace='products')), #spostato nell altro urls
    # con namespace da il nome a tutto iò che è dentro include
    # che dovrà essere richaimato con namespace: url name speicfico

#     path('products/', ProductListView.as_view()), #spostato nell altro urls
#     path('products-fbv/', product_list_view),

# # posso chiamarli id o pk a mio piacimento
#     # path('products/<int:pk>', ProductDetailView.as_view()),
#     path('products/<str:slug>', ProductDetailSlugView.as_view()),
#     path('products-fbv/<int:pk>', product_detail_view),

#     path('featured/', ProductFeaturedListView.as_view()),
#     path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),

    path('', include("search.urls", namespace='search')),

    # path('cart/', cart_home, name="cart"),
    path('cart/', include("carts.urls", namespace="cart")),

    path('api/cart/', cart_detail_api_view, name="api-cart"),

    # path('', include("carts.urls", namespace='carts')),

    path("logout/", LogoutView.as_view(), name="logout"),

    path('register/guest/', guest_register_view, name="guest_register"),

    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'), 

    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'), 

]

# setup e serve local e media files - python ecomemrce
# per gli static files
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

app_name = "products"


from products.views import (
    ProductListView, 
    # product_list_view, 
    # ProductDetailView, 
    ProductDetailSlugView,
    # product_detail_view,
    # ProductFeaturedListView,
    # ProductFeaturedDetailView,
    
)


urlpatterns = [
    
    # path('admin/', admin.site.urls),

    # path('', home_page, name="home"),
    # path('about/', about_page, name="about"),
    # path('contact/', contact_page, name="contact"),
    # path('login/', login_page, name="login"),
    # path('register/', register_page, name="register"),

    path('products/', ProductListView.as_view(), name="list"), #spostato nell altro urls
    # path('products-fbv/', product_list_view),

# posso chiamarli id o pk a mio piacimento
    # path('products/<int:pk>', ProductDetailView.as_view()),
    path('products/<str:slug>', ProductDetailSlugView.as_view(), name="detail"), #spostato nell altro urls
    # path('products-fbv/<int:pk>', product_detail_view),

    # path('featured/', ProductFeaturedListView.as_view()),
    # path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),


    
]

python_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# sarebbe meglio importarle nominativamente
# from . import views
from .views import home_page, about_page, contact_page

# per gli static files
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView

from carts.views import cart_home

from accounts.views import login_page, register_page

from django.contrib.auth.views import LogoutView

from accounts.views import guest_register_view

from addresses.views  import checkout_address_create_view
from addresses.views  import checkout_address_reuse_view

# from products.views import (
#     ProductListView, 
#     product_list_view, 
#     ProductDetailView, 
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
# )


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_page, name="home"),
    path('about/', about_page, name="about"),
    path('contact/', contact_page, name="contact"),
    path('login/', login_page, name="login"),
    path('register/', register_page, name="register"),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),

    path('', include("products.urls", namespace='products')), #spostato nell altro urls
    # con namespace da il nome a tutto iò che è dentro include
    # che dovrà essere richaimato con namespace: url name speicfico

#     path('products/', ProductListView.as_view()), #spostato nell altro urls
#     path('products-fbv/', product_list_view),

# # posso chiamarli id o pk a mio piacimento
#     # path('products/<int:pk>', ProductDetailView.as_view()),
#     path('products/<str:slug>', ProductDetailSlugView.as_view()),
#     path('products-fbv/<int:pk>', product_detail_view),

#     path('featured/', ProductFeaturedListView.as_view()),
#     path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),

    path('', include("search.urls", namespace='search')),

    # path('cart/', cart_home, name="cart"),
    path('cart/', include("carts.urls", namespace="cart")),

    # path('', include("carts.urls", namespace='carts')),

    path("logout/", LogoutView.as_view(), name="logout"),

    path('register/guest/', guest_register_view, name="guest_register"),

    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'), 

    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'), 

]

# setup e serve local e media files - python ecomemrce
# per gli static files
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<!-- aggiuntonper far applicare il css al foglio -->
<link rel="stylesheet" href='{% static "css/main.css" %}'>

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- awesome font css -->
<!-- not working -->
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"s"> -->

<!-- jQuery-confirm css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

templates/base/js.html
{% load static %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<!-- Optional JavaScript -->

<!-- jQuery -->
<!-- slim is missing ajax - remove the slim pattern form url -->
<!-- delete integrity and crossorigin because we want to change the files. then remove the Slim pattenr form string -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <!-- popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
    <!-- bootstrap.js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
<!-- jQuery-confirm JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- awesome font js -->
    <script src="https://kit.fontawesome.com/208306a8e2.js" crossorigin="anonymous"></script>


<!-- django secure ajax JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- ecommerce custom JS -->
<script src='{% static "js/ecommerce.js" %}'></script>

templates/base/navbar.html
<!-- aliases url -->
<!-- salvo in una variabile l'url che mi manda a una apgina -->

{% load static %}

{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as home_url %}
{% url 'register' as register_url %}
{% url 'carts:home' as cart_url %}
{% url 'admin:index' as admin_url %}
<!-- {% url 'admin:logout' as admin_logout_url %} -->
{% url 'logout' as logout_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class='container'>

    <a class="navbar-brand" href="{{ home_url }}"></a>
    {% comment %} <img src="{% static 'img/bootstrap.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> {% endcomment %}
    
    {% if brand_name %} {{ brand_name}} {% else %} complete eCommerce brane name {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'products:list' %}">Products</a>
          </li>

          <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'carts:home' %}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span><i class="fas fa-shopping-cart" aria-hidden="true"></i></a>
          </li>

          {% if not request.user.is_authenticated %}
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% else %}

          <li class="nav-item {% if request.path == admin_url %}active{% endif %}">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>

          <li class="nav-item {% if request.path == logout_url %}active{% endif %}"></li>
            <!-- <a class="nav-link" href="{% url 'logout' %}">Logout</a> -->
            <a class="nav-link" href="{{ logout_url }}">Logout</a>
          </li>
          {% endif %}



        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->

        <!-- <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->

      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>



  </div>
  </nav>